# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exampleservice.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='exampleservice.proto',
  package='com.eventbrite.grpckotlintutorial',
  syntax='proto3',
  serialized_options=b'\n\'com.eventbrite.grpckotlintutorial.protoB\014ExampleProtoP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14\x65xampleservice.proto\x12!com.eventbrite.grpckotlintutorial\"\"\n\x10ItsFridayRequest\x12\x0e\n\x06option\x18\x01 \x01(\t\"%\n\x11ItsFridayResponse\x12\x10\n\x08response\x18\x01 \x01(\t2\x89\x01\n\rFridayService\x12x\n\tItsFriday\x12\x33.com.eventbrite.grpckotlintutorial.ItsFridayRequest\x1a\x34.com.eventbrite.grpckotlintutorial.ItsFridayResponse\"\x00\x42\x39\n\'com.eventbrite.grpckotlintutorial.protoB\x0c\x45xampleProtoP\x01\x62\x06proto3'
)




_ITSFRIDAYREQUEST = _descriptor.Descriptor(
  name='ItsFridayRequest',
  full_name='com.eventbrite.grpckotlintutorial.ItsFridayRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='option', full_name='com.eventbrite.grpckotlintutorial.ItsFridayRequest.option', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=93,
)


_ITSFRIDAYRESPONSE = _descriptor.Descriptor(
  name='ItsFridayResponse',
  full_name='com.eventbrite.grpckotlintutorial.ItsFridayResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='com.eventbrite.grpckotlintutorial.ItsFridayResponse.response', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=132,
)

DESCRIPTOR.message_types_by_name['ItsFridayRequest'] = _ITSFRIDAYREQUEST
DESCRIPTOR.message_types_by_name['ItsFridayResponse'] = _ITSFRIDAYRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ItsFridayRequest = _reflection.GeneratedProtocolMessageType('ItsFridayRequest', (_message.Message,), {
  'DESCRIPTOR' : _ITSFRIDAYREQUEST,
  '__module__' : 'exampleservice_pb2'
  # @@protoc_insertion_point(class_scope:com.eventbrite.grpckotlintutorial.ItsFridayRequest)
  })
_sym_db.RegisterMessage(ItsFridayRequest)

ItsFridayResponse = _reflection.GeneratedProtocolMessageType('ItsFridayResponse', (_message.Message,), {
  'DESCRIPTOR' : _ITSFRIDAYRESPONSE,
  '__module__' : 'exampleservice_pb2'
  # @@protoc_insertion_point(class_scope:com.eventbrite.grpckotlintutorial.ItsFridayResponse)
  })
_sym_db.RegisterMessage(ItsFridayResponse)


DESCRIPTOR._options = None

_FRIDAYSERVICE = _descriptor.ServiceDescriptor(
  name='FridayService',
  full_name='com.eventbrite.grpckotlintutorial.FridayService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=135,
  serialized_end=272,
  methods=[
  _descriptor.MethodDescriptor(
    name='ItsFriday',
    full_name='com.eventbrite.grpckotlintutorial.FridayService.ItsFriday',
    index=0,
    containing_service=None,
    input_type=_ITSFRIDAYREQUEST,
    output_type=_ITSFRIDAYRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FRIDAYSERVICE)

DESCRIPTOR.services_by_name['FridayService'] = _FRIDAYSERVICE

# @@protoc_insertion_point(module_scope)
